name = "myapp"
account_id = "cfk_t6lBuKcTfaGHjKXcQmWX2z1BBpbGfeeFQuYsTuUS9da96e3c"
workers_dev = true

# Configure this as a static site
[[site]]
bucket = "./dist"          # Path to Vite's build output
entry-point = "workers-site"  